name: ci

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  validate-gradle-wrapper:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    if: github.repository == 'cheonjaewoong/buildconfig-gradle-plugin'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.repository == 'cheonjaewoong/buildconfig-gradle-plugin'
    needs: validate-gradle-wrapper
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 8

      - name: Run test
        run: ./gradlew test

  release:
    name: Publish Release
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/*') && (github.repository == 'cheonjaewoong/buildconfig-gradle-plugin') }}
    needs: [validate-gradle-wrapper, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 8

      - name: Publish to Maven Central
        run: ./gradlew publish --no-daemon --no-parallel --stacktrace
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_S01_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_S01_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_KEY_PASSWORD }}
